# Día 7 · Unidad 7 — pandas y NumPy (III): DataFrames — creación, lectura y columnas

**Objetivos de aprendizaje**
- Explicar qué es un DataFrame y cómo se relaciona con las Series del notebook anterior.
- Leer datos desde CSV y Excel con `read_csv`/`read_excel`.
- Leer los atributos básicos de un DataFrame (`shape`, `columns`, `dtypes`, `index`, `values`).
- Renombrar columnas de varias formas.

**Duración estimada:** 60-75 minutos.

**Requisitos previos:** `02_teoria_series.ipynb` de este mismo día.

## 1. Qué es un DataFrame

Un [`DataFrame`](https://pandas.pydata.org/docs/reference/frame.html) es el eje central de pandas: el equivalente a una hoja de cálculo de Excel o a una tabla de una base de datos. Es una estructura **bidimensional e indexada**: un conjunto de Series (columnas), potencialmente de tipos distintos entre sí, que comparten el mismo índice de filas.

En otras palabras: cada columna de un DataFrame es una `Series`, y todas comparten el mismo índice.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Un DataFrame se puede crear directamente desde un diccionario de listas
df_ejemplo = pd.DataFrame(
    data={
        "poliza_id": ["POL001", "POL002", "POL003"],
        "producto": ["AUTO", "HOGAR", "VIDA"],
        "prima_anual": [420.0, 310.5, 275.0],
    }
)
df_ejemplo

  poliza_id producto  prima_anual
0    POL001     AUTO        420.0
1    POL002    HOGAR        310.5
2    POL003     VIDA        275.0

## 2. Leer un DataFrame desde un archivo

En la práctica, casi nunca vas a teclear los datos a mano: los vas a **leer** desde un archivo externo. A partir de aquí trabajaremos con `cartera_polizas.csv`, la cartera de pólizas sintética de la aseguradora ficticia "Fenix Seguros" que usaremos durante el resto del curso (documentada en `data/generators/README.md`).

### CSV

Un archivo `.csv` (*Comma Separated Values*) es un archivo de texto plano que separa columnas con comas (a veces con `;` o `|`). Se lee con [`pd.read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html):

In [3]:
cartera = pd.read_csv("../data/raw/cartera_polizas.csv")
cartera.head()

,poliza_id,asegurado_id,nombre_asegurado,edad_tomador,producto,provincia,canal_venta,fecha_alta,fecha_baja,prima_anual,franquicia,anulada
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True
2,POL100002,AS20002,Maite Tudela-Sainz,22,HOGAR,Valencia,agente,2023-07-02,NaN,207.32,150,False
3,POL100003,AS20003,Abel de Cano,68,AUTO,Vizcaya,correduria,2023-02-28,NaN,540.71,300,False
4,POL100004,AS20004,Sebastian Augusto Sancho Alberdi,76,AUTO,Vizcaya,correduria,2022-01-26,NaN,589.46,450,False

> ⚠️ **Error típico**: usar una ruta relativa que no coincide con el directorio de trabajo (`cwd`) desde el que se ejecuta el notebook. En este curso, cada notebook se ejecuta con el `cwd` en su propia carpeta (`dia_07_pandas_numpy/`), así que para llegar a `data/raw/` hay que **subir un nivel** con `../`. Si ves `FileNotFoundError`, lo primero que hay que comprobar es desde dónde se está ejecutando el notebook — no asumas que la ruta está mal escrita sin comprobar el directorio de trabajo actual (`import os; os.getcwd()`).

### Excel

Excel no es el formato más eficiente para guardar datos, pero sí uno de los más prácticos para compartir información con perfiles no técnicos. Se lee con [`pd.read_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html), que requiere tener instalado `openpyxl` (ya está en `requirements.txt` del curso).

No tenemos un `.xlsx` de ejemplo todavía en `data/raw/`, así que generamos uno rápido a partir del propio `cartera`, solo para ver cómo se leería de vuelta — es exactamente el mismo patrón que usarías con un Excel real que os pase alguien del departamento comercial.

In [4]:
cartera.head(20).to_excel("_ejemplo_temporal.xlsx", sheet_name="cartera", index=False)

cartera_excel = pd.read_excel("_ejemplo_temporal.xlsx", sheet_name="cartera")
cartera_excel.head()

,poliza_id,asegurado_id,nombre_asegurado,edad_tomador,producto,provincia,canal_venta,fecha_alta,fecha_baja,prima_anual,franquicia,anulada
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True
2,POL100002,AS20002,Maite Tudela-Sainz,22,HOGAR,Valencia,agente,2023-07-02,NaN,207.32,150,False
3,POL100003,AS20003,Abel de Cano,68,AUTO,Vizcaya,correduria,2023-02-28,NaN,540.71,300,False
4,POL100004,AS20004,Sebastian Augusto Sancho Alberdi,76,AUTO,Vizcaya,correduria,2022-01-26,NaN,589.46,450,False

In [5]:
import os

os.remove("_ejemplo_temporal.xlsx")  # limpiamos el archivo temporal, no forma parte del dataset del curso

`read_excel()` admite parámetros muy parecidos a `read_csv()` (`sheet_name`, `skiprows`, `usecols`...) para lidiar con libros de Excel que no tienen los datos perfectamente alineados desde la primera fila y columna — algo muy habitual cuando el archivo lo ha preparado alguien a mano, con cabeceras, celdas combinadas o varias tablas en la misma hoja.

## 3. Atributos básicos

### `.head()` / `.tail()`

Ya los conoces de las Series — funcionan igual sobre un DataFrame.

In [6]:
cartera.head()

,poliza_id,asegurado_id,nombre_asegurado,edad_tomador,producto,provincia,canal_venta,fecha_alta,fecha_baja,prima_anual,franquicia,anulada
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True
2,POL100002,AS20002,Maite Tudela-Sainz,22,HOGAR,Valencia,agente,2023-07-02,NaN,207.32,150,False
3,POL100003,AS20003,Abel de Cano,68,AUTO,Vizcaya,correduria,2023-02-28,NaN,540.71,300,False
4,POL100004,AS20004,Sebastian Augusto Sancho Alberdi,76,AUTO,Vizcaya,correduria,2022-01-26,NaN,589.46,450,False

In [7]:
cartera.tail(3)

,poliza_id,asegurado_id,nombre_asegurado,edad_tomador,producto,provincia,canal_venta,fecha_alta,fecha_baja,prima_anual,franquicia,anulada
2997,POL102997,AS20397,Fausto Chaves-Valero,84,VIDA,A Coruna,telefono,2021-10-28,NaN,462.85,0,False
2998,POL102998,AS20398,Patricia Emiliana Peñalver Vigil,39,HOGAR,Alicante,online,2023-04-22,NaN,271.83,150,False
2999,POL102999,AS20399,Sonia Zabaleta,72,VIDA,Barcelona,agente,2024-05-09,NaN,260.64,0,False

### `.shape`

Devuelve una tupla `(número de filas, número de columnas)`.

In [8]:
print("Forma de la cartera:", cartera.shape)
print(f"{cartera.shape[0]} pólizas, {cartera.shape[1]} columnas")

Forma de la cartera: (3000, 12)
3000 pólizas, 12 columnas

### `.index` y `.columns`

In [9]:
print(cartera.index)
print(cartera.columns)

RangeIndex(start=0, stop=3000, step=1)
Index(['poliza_id', 'asegurado_id', 'nombre_asegurado', 'edad_tomador',
       'producto', 'provincia', 'canal_venta', 'fecha_alta', 'fecha_baja',
       'prima_anual', 'franquicia', 'anulada'],
      dtype='object')

### `.dtypes`

El tipo de dato que pandas ha asignado a cada columna — imprescindible revisarlo nada más cargar cualquier dataset nuevo.

In [10]:
cartera.dtypes

poliza_id            object
asegurado_id         object
nombre_asegurado     object
edad_tomador          int64
producto             object
provincia            object
canal_venta          object
fecha_alta           object
fecha_baja           object
prima_anual         float64
franquicia            int64
anulada                bool
dtype: object

Fíjate en `fecha_alta` y `fecha_baja`: pandas las ha leído como `object` (texto), no como fecha, porque `read_csv()` no adivina tipos de fecha por defecto. Si necesitas operar con ellas como fechas de verdad (restar fechas, extraer el año...), hay que decírselo explícitamente con `parse_dates`:

In [11]:
cartera_fechas = pd.read_csv(
    "../data/raw/cartera_polizas.csv",
    parse_dates=["fecha_alta", "fecha_baja"],
)
cartera_fechas.dtypes

poliza_id                   object
asegurado_id                object
nombre_asegurado            object
edad_tomador                 int64
producto                    object
provincia                   object
canal_venta                 object
fecha_alta          datetime64[ns]
fecha_baja          datetime64[ns]
prima_anual                float64
franquicia                   int64
anulada                       bool
dtype: object

> 📊 **En Excel esto sería...** como una celda que "parece" una fecha pero está formateada como texto: visualmente es indistinguible, pero no puedes restarle otra fecha ni usarla en un filtro de fechas hasta que cambias su formato de celda. `parse_dates` es el equivalente de decirle a pandas "formatea estas columnas como fecha".

### `.values`

Los datos del DataFrame como una matriz de NumPy — de nuevo, la misma conexión que viste en Series.

In [12]:
cartera.head(3).values

array([['POL100000', 'AS20000', 'Feliciano Valverde Vigil', 60, 'AUTO',
        'Alicante', 'correduria', '2021-08-27', '2022-11-24', 455.69,
        450, True],
       ['POL100001', 'AS20001', 'Vasco Godoy Rivero', 54, 'HOGAR',
        'Madrid', 'online', '2023-06-25', '2024-04-01', 274.72, 300,
        True],
       ['POL100002', 'AS20002', 'Maite Tudela-Sainz', 22, 'HOGAR',
        'Valencia', 'agente', '2023-07-02', nan, 207.32, 150, False]],
      dtype=object)

**Para ti:** carga `siniestros.csv` (también en `data/raw/`) en una variable `siniestros`, y comprueba su `.shape` y `.dtypes`. ¿Alguna columna debería tratarse como fecha y no lo está?

In [13]:
# Tu código aquí

## 4. Nombres de columnas: acceder, renombrar

Las columnas también son accesibles como atributo (`df.columna`), aunque la forma general y más segura es `df["columna"]` — lo verás en detalle en el próximo notebook. Para renombrarlas, hay dos vías principales.

### Modificar `.columns` directamente

In [14]:
columnas_originales = cartera.columns.tolist()
print(columnas_originales[:4])

cartera_mayus = cartera.copy()
cartera_mayus.columns = [c.upper() for c in cartera_mayus.columns]
cartera_mayus.head(2)

['poliza_id', 'asegurado_id', 'nombre_asegurado', 'edad_tomador']

,POLIZA_ID,ASEGURADO_ID,NOMBRE_ASEGURADO,EDAD_TOMADOR,PRODUCTO,PROVINCIA,CANAL_VENTA,FECHA_ALTA,FECHA_BAJA,PRIMA_ANUAL,FRANQUICIA,ANULADA
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True

Esto reemplaza **todos** los nombres de golpe, en el mismo orden — hay que tener cuidado de no desalinear nombres y columnas si se hace a mano.

### `.rename()`

Más flexible: permite cambiar solo algunas columnas, indicando explícitamente cuál va a cuál con un diccionario `{nombre_actual: nombre_nuevo}`.

In [15]:
cartera.rename(columns={"poliza_id": "id_poliza", "prima_anual": "prima"}).head(2)

,id_poliza,asegurado_id,nombre_asegurado,edad_tomador,producto,provincia,canal_venta,fecha_alta,fecha_baja,prima,franquicia,anulada
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True

Por defecto, `.rename()` devuelve una **copia** con el cambio aplicado — el DataFrame original (`cartera`) no se modifica. Para que el cambio persista sobre la variable original hace falta `inplace=True`, o reasignar el resultado (`cartera = cartera.rename(...)`).

In [16]:
print("¿Sigue igual el original?", "poliza_id" in cartera.columns)

¿Sigue igual el original? True

También se puede renombrar de forma sistemática con una función, exactamente igual que con una *list comprehension* sobre `.columns`:

In [17]:
cartera.rename(columns=str.upper).head(2)

,POLIZA_ID,ASEGURADO_ID,NOMBRE_ASEGURADO,EDAD_TOMADOR,PRODUCTO,PROVINCIA,CANAL_VENTA,FECHA_ALTA,FECHA_BAJA,PRIMA_ANUAL,FRANQUICIA,ANULADA
0,POL100000,AS20000,Feliciano Valverde Vigil,60,AUTO,Alicante,correduria,2021-08-27,2022-11-24,455.69,450,True
1,POL100001,AS20001,Vasco Godoy Rivero,54,HOGAR,Madrid,online,2023-06-25,2024-04-01,274.72,300,True

> ⚠️ **Error típico**: escribir mal una clave del diccionario en `.rename(columns={...})` (una errata, mayúsculas distintas...). pandas **no avisa** si la clave no coincide con ninguna columna existente: simplemente no renombra nada y sigue sin error. Conviene comprobar el resultado (`.columns`) después de renombrar, no dar por hecho que ha funcionado.

In [18]:
# "poliza_ID" con mayúscula no coincide con la columna real "poliza_id" -> no pasa nada, no hay error
resultado = cartera.rename(columns={"poliza_ID": "id_poliza"})
print("poliza_id" in resultado.columns, "id_poliza" in resultado.columns)

True False

**Para ti:** sobre `siniestros` (el DataFrame que cargaste antes), renombra la columna `importe_pagado` a `importe` y `fecha_siniestro` a `fecha`, guardando el resultado en una nueva variable `siniestros_renombrado`. Comprueba con un `assert` que las columnas nuevas existen y las viejas ya no.

In [19]:
# Tu código aquí

## Resumen

- Un DataFrame es una tabla bidimensional: un conjunto de Series (columnas) que comparten el mismo índice de filas — el equivalente de pandas a una hoja de cálculo.
- Se lee desde archivo con `pd.read_csv()` o `pd.read_excel()`; las rutas relativas dependen de desde dónde se ejecuta el notebook (`../data/raw/...` desde la carpeta del día).
- `read_csv()` no detecta fechas por defecto — hay que indicarlo con `parse_dates`, o esas columnas quedan como texto (`dtype object`) aunque "parezcan" fechas.
- Atributos básicos: `.shape` (filas, columnas), `.columns`, `.index`, `.dtypes` (revísalo siempre al cargar un dataset nuevo) y `.values` (la matriz de NumPy subyacente).
- Renombrar columnas: `.columns = [...]` sustituye todos los nombres de golpe; `.rename(columns={...})` cambia solo las indicadas y, por defecto, devuelve una copia (usa `inplace=True` o reasigna la variable para que persista).
- `.rename()` no avisa si una clave del diccionario no coincide con ninguna columna real — comprueba siempre el resultado.

**Siguiente:** `04_teoria_seleccion_filtrado_nulos.ipynb`, donde entramos en el corazón del día: seleccionar, filtrar, y limpiar nulos y duplicados — con el bloque de IA de traducción de lógica Excel a pandas.